
const games=[
{name:'المصاقيل',type:'مهارية',region:'منطقة نجد',description:'لعبة شعبية تعتمد على الكرات الصغيرة أو المصاقيل، وتحتاج إلى الدقة والتركيز في التصويب.',img:'assets/card-marbles.webp',alt:'رسم طفلين يلعبان بالمصاقيل الملونة على الأرض'},
{name:'العميان',type:'جماعية',region:'مناطق متعددة',description:'لعبة جماعية تُعصب فيها إحدى اللاعبات وتحاول الإمساك بزميلاتها اعتمادًا على السمع والحركة.',img:'assets/card-blindfold.webp',alt:'رسم طفلين يلعبان العميان وأحدهما معصوب العينين'},
{name:'الدحلة',type:'مهارية',region:'منطقة الجنوب',description:'لعبة حركية تعتمد على دفع الطوق أو الدحلة ومتابعته أثناء الحركة.',img:'assets/card-hoop.webp',alt:'رسم طفل يدحرج طوقًا كبيرًا بعصا'},
{name:'خمس حصيات',type:'مهارية',region:'مناطق متعددة',description:'لعبة مهارية تعتمد على التقاط الحصى أو الكرات الصغيرة بحركات سريعة ومتتابعة.',img:'assets/card-five-stones.webp',alt:'رسم طفلين يلعبان بالحصيات الصغيرة'},
{name:'شد الحبل',type:'جماعية',region:'مناطق متعددة',description:'لعبة جماعية تقوم على التنافس بين فريقين في سحب الحبل.',img:'assets/card-tug.webp',alt:'رسم فريقين من الأطفال يسحبون الحبل'},
{name:'قلب الصاع',type:'حركية',region:'منطقة الوسطى',description:'لعبة حركية يظهر فيها اللاعب دورانًا أو قلبة جسدية، وتحتاج إلى توازن وخفة حركة.',img:'assets/card-flip.webp',alt:'رسم يوضح حركة قلب الصاع واللاعب في أثناء القلب'},
{name:'النكسيسا',type:'جماعية',region:'المنطقة الغربية',description:'لعبة جماعية حركية تقوم على الانتقال السريع والتنسيق بين المشاركات.',img:'assets/card-under-bar.webp',alt:'رسم أطفال يحاولون المرور أسفل عارضة في لعبة النكسيسا'},
{name:'القصرة أم ست',type:'مهارية',region:'المنطقة الشرقية',description:'لعبة أرضية تعتمد على مربعات أو تقسيمات مرسومة وتحتاج إلى تركيز وتنظيم للحركة.',img:'assets/card-grid.webp',alt:'رسم طفلين يلعبان على مربعات مرسومة في الأرض'},
{name:'المتابعة',type:'مهارية',region:'مناطق متعددة',description:'لعبة تعتمد على متابعة الإشارة أو الحركة وتنفيذها بسرعة ودقة.',img:'assets/card-follow.webp',alt:'رسم لاعب واقف وآخر جالس مع أسهم توضّح حركة المتابعة'},
{name:'الحنفرة',type:'حركية',region:'المنطقة الجنوبية',description:'لعبة حركية تعتمد على القفز أو اجتياز عائق مع قدر من الرشاقة والسرعة.',img:'assets/card-jump.webp',alt:'رسم طفل يقفز عند جذع خشبي في لعبة الحنفرة'},
{name:'الدبق',type:'مهارية',region:'المنطقة الشمالية',description:'لعبة شعبية تستخدم الحصى أو القطع الصغيرة وتحتاج إلى تقدير المسافة والدقة.',img:'assets/card-pebbles.webp',alt:'رسم فتاتين تلعبان بالحصى على الأرض'}
];
const grid=document.getElementById('gamegrid');function render(){grid.innerHTML='';games.forEach((g,i)=>{let el=document.createElement('article');el.className='game';el.innerHTML=`<div class="game-media"><img loading="lazy" decoding="async" src="${g.img}" alt="${g.alt}" width="900" height="600"></div><div class="content"><small>${g.type} · بطاقة ${i+1}</small><h3>${g.name}</h3><small style="display:block;margin-top:8px">${g.region}</small><button type="button">عرض البطاقة</button></div>`;el.querySelector('button').onclick=()=>{document.getElementById('detail-title').textContent=g.name;document.getElementById('detail-img').src=g.img;document.getElementById('detail-img').alt=g.alt;document.getElementById('detail-text').textContent=g.description+' · '+g.region;document.getElementById('detail').showModal()};grid.append(el)})}render();
const qs=[['ما الهدف الأساسي من الألعاب الشعبية؟',['التسلية والتعاون وتنمية المهارات','استخدام الأجهزة الإلكترونية','اللعب الفردي فقط'],0],['أي لعبة تعتمد على القفز بين مربعات مرسومة؟',['شد الحبل','الحجلة','الدوامة'],1],['ما الذي تنمّيه ألعاب الحصى غالبًا؟',['الدقة والتركيز','سرعة الكتابة','استخدام الهاتف'],0],['ما القيمة التي نتعلمها من الألعاب الجماعية؟',['التعاون واحترام الدور','تجاهل الآخرين','الابتعاد عن الفريق'],0],['أي الألعاب تعتمد على تنسيق الحركة بين لاعبتين تمسكان الحبل ولاعبة تقفز؟',['القفز بالحبل','الغميضة','الدوامة'],0],['ما الفرق بين الألعاب الشعبية وألعاب الفيديو؟',['الألعاب الشعبية غالبًا تعتمد على التفاعل المباشر والحركة','الألعاب الشعبية تحتاج الإنترنت دائمًا','لا يوجد أي فرق'],0],['ما فائدة توثيق الألعاب الشعبية؟',['حفظ التراث ونقله للأجيال','منع اللعب','نسيان العادات'],0],['ما الذي تعبّر عنه الفنون الأدائية التراثية؟',['الهوية والذاكرة الثقافية','الألعاب الإلكترونية فقط','الرياضيات فقط'],0]];let answers={};function quizRender(){let holder=document.getElementById('questions');holder.innerHTML='';qs.forEach((q,i)=>{let el=document.createElement('div');el.className='question';el.innerHTML=`<h3>${i+1}. ${q[0]}</h3><div class="answers"></div><p class="result" aria-live="polite"></p>`;let buttons=el.querySelector('.answers');q[1].forEach((opt,j)=>{let b=document.createElement('button');b.textContent=opt;b.className=answers[i]===j?'selected':'';b.onclick=()=>{answers[i]=j;quizRender()};buttons.append(b)});if(answers[i]!==undefined)el.querySelector('.result').textContent=answers[i]===q[2]?'✓ إجابة صحيحة':'حاولي مرة أخرى';holder.append(el)});document.getElementById('total').textContent=`نتيجتك: ${qs.filter((q,i)=>answers[i]===q[2]).length} من ${qs.length}`};document.getElementById('reset').onclick=()=>{answers={};quizRender()};quizRender();
